export default [
  {
    id: new Date() + Math.random(),
    name: 'Ekaterina Tankova',
    address: {
      country: 'USA',
      state: 'West Virginia',
      city: 'Parkersburg',
      street: '2849 Fulton Street',
    },
    email: 'ekaterina.tankova@devias.io',
    phone: '304-428-3097',
    avatar: 'https://i.pravatar.cc/200?img=1',
    createdAt: 1555016400000,
  },
  {
    id: new Date() + Math.random(),
    name: 'Cao Yu',
    address: {
      country: 'USA',
      state: 'Bristow',
      city: 'Iowa',
      street: '1865  Pleasant Hill Road',
    },
    email: 'cao.yu@devias.io',
    avatar: 'https://i.pravatar.cc/200?img=2',
    phone: '712-351-5711',
    createdAt: 1555016400000,
  },
  {
    id: new Date() + Math.random(),
    name: 'Alexa Richardson',
    address: {
      country: 'USA',
      state: 'Georgia',
      city: 'Atlanta',
      street: '4894  Lakeland Park Drive',
    },
    email: 'alexa.richardson@devias.io',
    phone: '770-635-2682',
    avatar: 'https://i.pravatar.cc/200?img=3',
    createdAt: 1555016400000,
  },
  {
    id: new Date() + Math.random(),
    name: 'Anje Keizer',
    address: {
      country: 'USA',
      state: 'Ohio',
      city: 'Dover',
      street: '4158  Hedge Street',
    },
    email: 'anje.keizer@devias.io',
    avatar: 'https://i.pravatar.cc/200?img=4',
    phone: '908-691-3242',
    createdAt: 1554930000000,
  },
  {
    id: new Date() + Math.random(),
    name: 'Clarke Gillebert',
    address: {
      country: 'USA',
      state: 'Texas',
      city: 'Dallas',
      street: '75247',
    },
    email: 'clarke.gillebert@devias.io',
    phone: '972-333-4106',
    avatar: 'https://i.pravatar.cc/200?img=5',
    createdAt: 1554757200000,
  },
  {
    id: new Date() + Math.random(),
    name: 'Adam Denisov',
    address: {
      country: 'USA',
      state: 'California',
      city: 'Bakerfield',
      street: '317 Angus Road',
    },
    email: 'adam.denisov@devias.io',
    phone: '858-602-3409',
    avatar: 'https://i.pravatar.cc/200?img=6',
    createdAt: 1554670800000,
  },
  {
    id: new Date() + Math.random(),
    name: 'Ava Gregoraci',
    address: {
      country: 'USA',
      state: 'California',
      city: 'Redondo Beach',
      street: '2188  Armbrester Drive',
    },
    email: 'ava.gregoraci@devias.io',
    avatar: 'https://i.pravatar.cc/200?img=7',
    phone: '415-907-2647',
    createdAt: 1554325200000,
  },
  {
    id: new Date() + Math.random(),
    name: 'Emilee Simchenko',
    address: {
      country: 'USA',
      state: 'Nevada',
      city: 'Las Vegas',
      street: '1798  Hickory Ridge Drive',
    },
    email: 'emilee.simchenko@devias.io',
    phone: '702-661-1654',
    avatar: 'https://i.pravatar.cc/200?img=8',
    createdAt: 1523048400000,
  },
  {
    id: new Date() + Math.random(),
    name: 'Kwak Seong-Min',
    address: {
      country: 'USA',
      state: 'Michigan',
      city: 'Detroit',
      street: '3934  Wildrose Lane',
    },
    email: 'kwak.seong.min@devias.io',
    avatar: 'https://i.pravatar.cc/200?img=9',
    phone: '313-812-8947',
  },
  {
    id: new Date() + Math.random(),
    name: 'Merrile Burgett',
    address: {
      country: 'USA',
      state: 'Utah',
      city: 'Salt Lake City',
      street: '368 Lamberts Branch Road',
    },
    email: 'merrile.burgett@devias.io',
    phone: '801-301-7894',
    avatar: 'https://i.pravatar.cc/200?img=10',
    createdAt: 1522702800000,
  },
];
